# Generated by Django 5.2.1 on 2025-05-22 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_at'], 'verbose_name': 'Задание', 'verbose_name_plural': 'Задания'},
        ),
    ]
