# Generated by Django 5.2.1 on 2025-06-01 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_task_is_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='is_completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
