# Generated by Django 5.2.1 on 2025-06-01 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_task_options_alter_task_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='is_private',
            field=models.BooleanField(verbose_name='Приватная'),
        ),
    ]
